services:
  auth:
    build:
      context: authservice-go
    env_file:
      - authservice-go/env/local.env
    ports:
      - "8081:8081"
  service:
    build:
      context: service-go
    depends_on:
      - auth
    env_file:
      - service-go/env/local.env
    environment:
      AUTH_SERVER_ADDR: auth:8081
    ports:
      - "8080:8080"
  client:
    build:
      context: client-go
    depends_on:
      - auth
      - service
    environment:
      SERVER_ADDR: service:8080
      AUTH_SERVER_ADDR: auth:8081
    command:
      - -u
      - example
      - -p
      - helloworld
